name: GetScreen Windows 10 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=DarkzVV@proton.me" > secrets.txt
         Invoke-WebRequest -Uri "https://gitlab.com/chamod12/getscrn-win10-github-rdp/-/raw/main/down.bat" -OutFile "down.bat"
         cmd /c down.bat
                   Invoke-WebRequest -Uri "https://gitlab.com/chamod12/anydesk-windows-rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c start.bat


      - name: Time Counter
        run: cmd /c loop.bat
